Repository akkupy/codeDump, pull requests merged in 2023-10, with the labels that each got.

#255 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#238 Shorter and readable code
  python/Fibonacci_Series.py
Labels: hacktoberfest-accepted

#240 Calculator/python
  cpp/sudoku_solver.cpp
  data_structure/topological_sort.py
  python/calculator_.py
  python/downward_traingle_pattern.py
  python/fibonacci_series.py
Labels: hacktoberfest-accepted

#242 fibonacci code added
  python/fibonacci_series.py
Labels: hacktoberfest-accepted

#246 Removed extra variable for swapping
  python/reverseString.py
Labels: hacktoberfest-accepted

#247 Code refactored and removed unecessary loops
  python/Count_Sort.py
Labels: hacktoberfest-accepted

#248 Implement Threads in Java #214
  java/threads.java
Labels: hacktoberfest-accepted

#249 Update Binarysearch.cpp
  cpp/Binarysearch.cpp
  java/OddOrEven.java
  java/Trafficlight.java
  java/waveprint.java
Labels: hacktoberfest-accepted

#250 Banking system management.cpp
  cpp/Banking system.cpp
Labels: hacktoberfest-accepted

#251 Sudoku Solver
  cpp/sudokusolver.cpp
Labels: hacktoberfest-accepted

#256 Create 02datatypesnvar.dart
  dart/02datatypesnvar.dart
Labels: hacktoberfest-accepted

#259 an analog watch using react and js
  web/analog-watch/.eslintrc.cjs
  web/analog-watch/.gitignore
  web/analog-watch/README.md
  web/analog-watch/index.html
  web/analog-watch/package-lock.json
  web/analog-watch/package.json
  web/analog-watch/postcss.config.js
  web/analog-watch/public/vite.svg
  web/analog-watch/src/App.jsx
  web/analog-watch/src/assets/react.svg
  web/analog-watch/src/components/AnalogWatch.css
  web/analog-watch/src/components/AnalogWatch.jsx
  web/analog-watch/src/index.css
  web/analog-watch/src/main.jsx
  web/analog-watch/tailwind.config.js
  web/analog-watch/vite.config.js
Labels: hacktoberfest-accepted

#258 Created cyclic sort
  java/Cyclic sort.java
Labels: hacktoberfest-accepted

#261 created tower of hanoi code in java
  java/towerOfHanoi.java
Labels: hacktoberfest-accepted

#262 Create Linear Search.java
  data_structure/Linear Search.java
Labels: hacktoberfest-accepted

#263 Create SelectionSort.java
  data_structure/SelectionSort.java
Labels: hacktoberfest-accepted

#264 Created simple linear regression.py
  python/simple linear regression.py
Labels: hacktoberfest-accepted

#266 Created a code to check armstrong number
  python/armstrong.py
Labels: hacktoberfest-accepted

#267 Double linkedlist in python
  data_structure/double_linkedlist.py
Labels: hacktoberfest-accepted

#268 tower of hanoi
  java/toi.java
Labels: hacktoberfest-accepted

#270 Tower of hanoi in java
  java/tower_of_hanoi.java
Labels: hacktoberfest-accepted, hacktoberfest2023

#271 Added twoSum in java
  java/TwoSum.java
Labels: hacktoberfest-accepted

#272 java op
  java/Freq.java
Labels: hacktoberfest-accepted

#273 First contribution
  cpp/sudokusolver.cpp
  data_structure/DoublyLinkedList.cpp
  python/fibonacci_series.py
Labels: hacktoberfest-accepted

#274 TreeTraversal Implementation In Java
  java/TreeTraversal.java
Labels: hacktoberfest-accepted

#275 Implement Kadane's Algorithm Program in Java
  data_structure/Kadane's Algorithm.java
Labels: hacktoberfest-accepted, hacktoberfest

#276 added spiralOrderTraversal.c
  c/spiralOrderTraversal.c
Labels: hacktoberfest-accepted, hacktoberfest

#278 Implement KnapSack Top Down Approach using Dynamic Programming
  java/KnapSackTopDown.java
Labels: hacktoberfest-accepted, hacktoberfest

#279 Create Secondmax.java
  java/Secondmax.java
Labels: hacktoberfest-accepted, hacktoberfest

#280 Create Pascal's triangle in python.py
  python/Pascal's triangle in python.py
Labels: hacktoberfest-accepted, hacktoberfest

#285 Create 03_String.dart
  dart/03_String.dart
Labels: hacktoberfest-accepted, hacktoberfest

#286 java
  java/MultiThread.java
Labels: hacktoberfest-accepted, hacktoberfest

#288 tower_of_hanoi.py
  python/tower_of_hanoi.py
Labels: hacktoberfest-accepted, hacktoberfest

#283 Create Maximum Value of an Ordered Triplet I.java
  java/Maximum Value of an Ordered Triplet I.java
Labels: hacktoberfest-accepted, hacktoberfest

#293 Create Prims.cpp
  cpp/Prims.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#294 Create FloydWarshall.cpp
  cpp/FloydWarshall.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#295 added sudoku solver
  cpp/sudoku_solveroptimum.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#291 Downward Triangle Pattern in python
  python/downward_triangle_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#296 solved the daily checkin leetcode question
  LeetCodeQuestions/557. Reverse Words in a String III/main.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#298 Downward triangle Pattern in Python
  python/downward_triangle_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest

#299 Create FibonacciHeap.cpp
  cpp/FibonacciHeap.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#302 Create Dijkstras.cpp
  cpp/Dijkstras.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#303 added new code
  java/MaximalSquare.java
Labels: hacktoberfest-accepted, hacktoberfest

#304 Create Reverse words in a string III.py
  LeetCodeQuestions/Reverse words in a string III.py
Labels: hacktoberfest-accepted, hacktoberfest

#308 Cpp codes
  cpp/3 Sum Closest.cpp
  cpp/3 Sum.cpp
  cpp/4 Sum.cpp
  cpp/Letter Combinations of a phone number.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#309 Added armstrong program in c
  c/armstrong.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#311 RandomCodeGenerator
  web/Random-Code-Generator/css/normalize.css
  web/Random-Code-Generator/css/styles.css
  web/Random-Code-Generator/index.html
  web/Random-Code-Generator/js/script.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#312 Linkedist implementation of stack and bubble sort algorithm in C
  LeetCodeQuestions/paranthesis_matching_problem_stack.c
  data_structure/linked_list_stack_C.c
  java/multithread.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#313 Create bubbleSort.java
  data_structure/bubbleSort.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#315 added the binary search
  data_structure/BinarSeach.cpp
  java/multithread.java
  python/fibonacci_series.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#316 HackerRank-Solutions [1-5]
  HackerRank-Solutions/Python/arithmetic-operators.py
  HackerRank-Solutions/Python/division.py
  HackerRank-Solutions/Python/hello-world.py
  HackerRank-Solutions/Python/if-else.py
  HackerRank-Solutions/Python/loops.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#317 Weather-app
  web/note-app/index.html
  web/note-app/index.js
  web/note-app/style.css
  web/weather-app/index.html
  web/weather-app/index.js
  web/weather-app/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#318 Added the code for creation of a BST
  data_structure/BST.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#319 added binary search cpp
  cpp/binary_Search.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#321 TipCalculator
  web/tip-calculator/index.html
  web/tip-calculator/index.js
  web/tip-calculator/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#322 Created averageOfLevelsBT.java and added it to the Java folder
  java/averageOfLevelsBT.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#323 added sudoku solver in cpp
  cpp/sudoku_solver_opt.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#325 Added Bubble Sort
  java/multithread.java
  python/Bubble-Sort.py
  python/downward_triangle_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#327 MINICALENDAR
  web/mini-calendar/index.html
  web/mini-calendar/index.js
  web/mini-calendar/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#328 Added Insertion and Selection Sort using C language
  data_structure/insertion_sort.c
  data_structure/selection_sort.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#329 added merge sort algorithm in java
  data_structure/mergeSort.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#333 Added Insertion Sort
  python/Insertion-Sort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#337 Added an amazon scraper in python folder
  python/amazon_scraper/README.md
  python/amazon_scraper/amazon_scraper.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#338 Search in Rotated Array
  LeetCodeQuestions/33. Search in Rotated Sorted Array/cpp.cpp
  LeetCodeQuestions/33. Search in Rotated Sorted Array/java.java
  LeetCodeQuestions/33. Search in Rotated Sorted Array/python.py
  LeetCodeQuestions/50. Pow(x, n)/cpp.cpp
  LeetCodeQuestions/50. Pow(x, n)/java.java
  LeetCodeQuestions/50. Pow(x, n)/python.py
  LeetCodeQuestions/74. Search a 2D Matrix/cpp.cpp
  LeetCodeQuestions/74. Search a 2D Matrix/java.java
  LeetCodeQuestions/74. Search a 2D Matrix/python.py
  LeetCodeQuestions/77. Combinations/cpp.cpp
  LeetCodeQuestions/77. Combinations/java.java
  LeetCodeQuestions/77. Combinations/python.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#339 Create BinarySearch.py
  python/BinarySearch.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#340 Create Dijkastra.py
  python/Dijkastra.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#342 Added N-queens solution in to the java folder
  java/NQueens.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#343 Create FloyddWarshall.py
  python/FloyddWarshall.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#336 knapsack
  python/knapsack.py
Labels: hacktoberfest-accepted, hacktoberfest

#345 resolve Add the list of contributors at the footer of the readme.md file hacktoberfest #239
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#341 Create eucledean's gcd with time
  python/eucledean_gcd_with_time.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#347 Added Merge Sort
  python/Merge-sort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#350 Create BFS.py
  python/BFS.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#351 Create uniquesearchalgorithm.py
  python/uniquesearchalgorithm.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#352 Create linkedlistpython.py
  python/linkedlistpython.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#353 Create matchcasepython.py
  python/matchcasepython.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#354 Create 04_keyboard_input.dart
  dart/Dart/04_keyboard_input.dart
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#358 Added some Leetcode Solutions
  LeetCodeQuestions/FindMedianFromDataStream.cpp
  LeetCodeQuestions/ImplementQueueUsingStack.cpp
  LeetCodeQuestions/ImplementStackUsingQueue.cpp
  LeetCodeQuestions/JumpGame.cpp
  LeetCodeQuestions/MergeTwoSortedLinkedList.cpp
  LeetCodeQuestions/MinStack.cpp
  LeetCodeQuestions/MinimumAddToMakeParenthesisValid.cpp
  LeetCodeQuestions/ReverseInteger.cpp
  LeetCodeQuestions/SmallestRangeCoveringElementsFromKLists.cpp
  LeetCodeQuestions/SortColors.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#359 added the code for implementation of graph
  data_structure/graph.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#360 Update README.md
  LeetCodeQuestions/README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#361 Added python solution for leetcode 11
  LeetCodeQuestions/11-container-with-most-water.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#362 Added login page and binomial theorem projects using C
  c/binomial.c
  c/login_page.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#364 added python program which removes duplicate from given string
  python/remove_duplicate_from_string.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#365 Added DSA-LIST
  python/dsa-list.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#366 Create 05_Constans.dart
  dart/05_Constans.dart
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#368 Bubble Sort
  javascript/bubbleSort.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#369 implement binamry search in cpp
  cpp/Impelement_binary_search.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#371 Added Leetcode Dynamic Programming Solutions
  LeetCodeQuestions/BestTimeToBuyAndSellStockI.cpp
  LeetCodeQuestions/BestTimeToBuyAndSellStockII.cpp
  LeetCodeQuestions/BestTimeToBuyAndSellStockIII.cpp
  LeetCodeQuestions/BestTimeToBuyAndSellStockIV.cpp
  LeetCodeQuestions/BestTimeToBuyAndSellStockV.cpp
  LeetCodeQuestions/CombinationSum4.cpp
  LeetCodeQuestions/CountWaysToBuildGoodString.cpp
  LeetCodeQuestions/EditDistance.cpp
  LeetCodeQuestions/GuessNumberHigherOrLower.cpp
  LeetCodeQuestions/HouseRobber.cpp
  LeetCodeQuestions/LongestArithmeticSubsequence.cpp
  LeetCodeQuestions/LongestArithmeticSubsequencecOfGivenDifference.cpp
  LeetCodeQuestions/LongestCommonSubsequence.cpp
  LeetCodeQuestions/LongestPalindromicSubsequence.cpp
  LeetCodeQuestions/MaximalRectangle.cpp
  LeetCodeQuestions/MaximumHeightByStackingCuboids.cpp
  LeetCodeQuestions/MinCostClimbingStairs.cpp
  LeetCodeQuestions/MinimumCoinChange.cpp
  LeetCodeQuestions/MinimumCostForTickets.cpp
  LeetCodeQuestions/MinimumScoreTriangulationOfPolygon.cpp
  LeetCodeQuestions/MinimumSidewaysJumps.cpp
  LeetCodeQuestions/MinimumSwapsToMakeSequencesIncreasing.cpp
  LeetCodeQuestions/NumberOfDiceRollsWithTargetSum.cpp
  LeetCodeQuestions/PartitionEqualSubsetSum.cpp
  LeetCodeQuestions/PizzaWith3nSlices.cpp
  LeetCodeQuestions/ReducingDishes.cpp
  LeetCodeQuestions/RussianDolls.cpp
  LeetCodeQuestions/UncrossedLines.cpp
  LeetCodeQuestions/UniqueBinarySearchTrees.cpp
  LeetCodeQuestions/WildCardMatching.cpp
  cpp/ArticulationPoint.cpp
  cpp/BFSTraversal.cpp
  cpp/BellmanFordAlgorithm.cpp
  cpp/BridgesCriticalConnectionsInANetwork.cpp
  cpp/CreatingAndPrintingGraph.cpp
  cpp/DFSTraversal.cpp
  cpp/DijkstrasShortestPath.cpp
  cpp/DirectedGraphCycleDetectionBFS.cpp
  cpp/DirectedGraphCycleDetectionDFS.cpp
  cpp/ImplementationOfGraph.cpp
  cpp/KosarajusAlgorithm.cpp
  cpp/MinimumSpanningTreeUsingKrushkalsAlgorithm.cpp
  cpp/NegativeWeightCycle.cpp
  cpp/PrimsMST.cpp
  cpp/ShortestPathInUnweightedGraph.cpp
  cpp/ShortestPathInWeightedDirectedGraph.cpp
  cpp/TopologicalSort.cpp
  cpp/UndirectedGraphCycleDetectionUsingBFSandDFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#372 Update OddOrEven.java
  java/OddOrEven.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#373 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#374 Added cipher algo and address comparison of variables
  c/ROT13_cipher.c
  c/address_comparison.c
  c/caesar_cipher.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#375 Add files via upload
  Jupyter/Sentiment Analysis/Sentiment Analysis of Text Data.ipynb
  Jupyter/Sentiment Analysis/data/emoticons.txt
  Jupyter/Sentiment Analysis/data/empty
  Jupyter/Sentiment Analysis/data/test.csv
  Jupyter/Sentiment Analysis/data/train.csv
  Jupyter/Sentiment Analysis/wordlist.csv
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#376 Create letterCombinations.java and added it to leetcode folder
  LeetCodeQuestions/letterCombinations.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#378 Added a few hackerrank solutions
  HackerRank-Solutions/Python/find-the-runner-up-score.py
  HackerRank-Solutions/Python/list-comprehensions.py
  HackerRank-Solutions/Python/nested-lists.py
  HackerRank-Solutions/Python/print-function.py
  HackerRank-Solutions/Python/write-a-function.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#379 Added Color Flipper
  javascript/Color Flipper/app.js
  javascript/Color Flipper/hex.html
  javascript/Color Flipper/hex.js
  javascript/Color Flipper/index.html
  javascript/Color Flipper/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#380 PDF to Audio #356
  python/PDF to Audio/.DS_Store
  python/PDF to Audio/For Mac/main.py
  python/PDF to Audio/For Mac/readme.md
  python/PDF to Audio/For Ubuntu/main.py
  python/PDF to Audio/For Ubuntu/readme.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#382 Create Transpose_matrix.c
  c/Transpose_matrix.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#383 AVL tree
  cpp/AVL_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#384 Add Swap-Number file in Java Folder
  java/SwapNumbers.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#385 Add AVL Tree in C and Parentheses Check using stacks in C++
  cpp/Balanced_Paranthesis_Using_Stacks.cpp
  data_structure/AVL_Tree.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#386 Feature: Add Reverse List and Remove Nth Node from end Code
  data_structure/linked_list/removeNthNode.py
  data_structure/linked_list/reverse_linkedlist.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#387 Added Tree Questions
  cpp/BInaryTreeZigZagLevelOrderTraversal.cpp
  cpp/BinaryTreeInorderTraversal.cpp
  cpp/BinaryTreePostorderTraversal.cpp
  cpp/BinaryTreePreorderTraversal.cpp
  cpp/BinaryTreeRightSideView.cpp
  cpp/BottomViewOfBinaryTree.cpp
  cpp/BoudaryTraversalOfBinaryTree.cpp
  cpp/BurningTree.cpp
  cpp/ConstructTreeFromInorderAndPostorder.cpp
  cpp/ContructTreeFromInorderAndPreorder.cpp
  cpp/DiagonalTraversalOfBinaryTree.cpp
  cpp/DiameterOfBinaryTree.cpp
  cpp/FlattenABSTToSortedList.cpp
  cpp/FlattenBinaryTreeToLinkedList.cpp
  cpp/KSumPaths.cpp
  cpp/KthAncestorInATree.cpp
  cpp/KthSmallestInBST.cpp
  cpp/LargestBSTInATree.cpp
  cpp/LeftViewOfBinaryTree.cpp
  cpp/LowestCommonAncestorInABinaryTree.cpp
  cpp/LowestCommonAncestorInBinarySearchTree.cpp
  cpp/MaximumDepthOfBinaryTree.cpp
  cpp/MaximumSumOfNonAdjacentNodes.cpp
  cpp/MergeTwoBST.cpp
  cpp/MorrisTraversal.cpp
  cpp/PathSum.cpp
  cpp/PredecessorAndSuccessor.cpp
  cpp/SameTree.cpp
  cpp/SearchInBST.cpp
  cpp/SumOfTheLongestBloodLineOfATree.cpp
  cpp/SumTree.cpp
  cpp/TopViewBinaryTree.cpp
  cpp/TwoSumInABST.cpp
  cpp/ValidateBST.cpp
  cpp/VerticalOrderTraversalOfABianryTree.cpp
  cpp/VerticalTraversalOfBinaryTree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#388 Updated binomial.c
  c/binomial.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#389 Added Todo List
  web/todo-list/index.html
  web/todo-list/script.js
  web/todo-list/styles.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#393 Update area_shapes.java
  java/area_shapes.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#394 Create Sieve_of_Eratosthenes_Mohak1301
  cpp/Sieve_of_Eratosthenes.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#397 Create Dijkastra'sAlgo_Mohak1301
  javascript/Dijkastra's_Mohak1301.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#399 Create kruskal'salgo_Mohak1301
  javascript/kruskal'salgo.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#400 added all tree traversal methods in C
  data_structure/in_order_pre_order_and_post_order_traversal.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#403 binary search and graph implemented in C++
  cpp/binary_search.cpp
  cpp/graph.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#406 added few projects
  python/Area of sphere.py
  python/HandTrackingModule.py
  python/alarm_clock.py
  python/analyze.py
  python/area_plane_figure.py
  python/clasess.py
  python/dataset.py
  python/examining.py
  python/finger counting project.py
  python/import.py
  python/matrix.py
  python/run.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#407 Added gcd pgm in Java
  java/GCD.java
  web/php/hello.php
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#408 Hackerrank Solutions
  HackerRank-Solutions/Python/find-second-maximum-number-in-a-list.py
  HackerRank-Solutions/Python/find-the-runner-up-score.py
  HackerRank-Solutions/Python/finding-the-percentage.py
  HackerRank-Solutions/Python/list-comprehensions.py
  HackerRank-Solutions/Python/lists.py
  HackerRank-Solutions/Python/print-function.py
  HackerRank-Solutions/Python/string-split-and-join.py
  HackerRank-Solutions/Python/swap-case.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#409 compare two linked list, reverse linked list, and a problem on kaden's algo
  javascript/rockPaperScissor.js
  python/compare_two_linkedList.py
  python/reverse_linkedList.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#411 added solution for 3sum in cpp
  LeetCodeQuestions/15. 3sum.cpp
  LeetCodeQuestions/31. Next Permutation.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#412 #198 portfolio website added
  static-portfolio-templates/Syntax_Smiler_portfolio/aasuna.jpg
  static-portfolio-templates/Syntax_Smiler_portfolio/index.html
  static-portfolio-templates/Syntax_Smiler_portfolio/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#413 Problems from Trie, Backtracking, Heap, Stack, Greedy, etc
  cpp/FractionalKnapsack.cpp
  cpp/HelpClassmateOrNextSmallerInStack.cpp
  cpp/HuffmanEncoding.cpp
  cpp/LongestCommonPrefix.cpp
  cpp/MaxRectangle.cpp
  cpp/MergeKSortedArraysUsingHeap.cpp
  cpp/MergeTwoBinaryMaxHeaps.cpp
  cpp/MinimumCostOfRopes.cpp
  cpp/MinimumCostToMakeStringValid.cpp
  cpp/NQueenProblem.cpp
  cpp/NStacksInAnArray.cpp
  cpp/RatInAMazeProblem1.cpp
  cpp/ShopInCandyStore.cpp
  cpp/SpiralMatrix2.cpp
  cpp/TheCelebrityProblem.cpp
  cpp/peakMountain.cpp
  cpp/spiralMatrix.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#414 Adding an optimal approach to solve Stock Buy and Sell problem
  data_structure/stocksell.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#416 Rock Paper Scissor
  javascript/Rock_paper_scissor.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#418 Create symmetric_void_pattern.cpp
  cpp/symmetric_void_pattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#419 Added Subset Sum Using Dynamic Programming
  java/SubSetSumDp.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#420 Add HouseRobberIII C++
  LeetCodeQuestions/HouseRobberIII.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#421 Create checkPalindrome.cpp
  cpp/checkPalindrome.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#422 Add java code for intro-sort
  java/IntroSort.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#424 added selection-sort.py
  python/selection-sort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#431 Predicting Body Fat through Regression Algos of Machine Learning
  jupyterNotebook/BodyFat.ipynb
  jupyterNotebook/bodyfat.csv
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#433 Create checkArmStrong.cpp to check the armstrong number
  cpp/checkArmStrong.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#435 Add: connect to postgres database in golang
  go/database/.env
  go/database/connect-datatbase.go
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#436 Neonbutton
  web/Neon Button/index.html
  web/Neon Button/styles.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#438 Created numberDecrement.cpp file
  cpp/numberDecrement.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#441 Create countDigits.cpp
  cpp/countDigits.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#446 Created highest_lowest_frequency_with_hashing.cpp
  cpp/highest_lowest_frequency_with_hashing.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#448 add btree
  python/btree.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#449 Update Reverse_array.c
  c/Reverse_array.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#450 Java code for depth first search
  java/Graph.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#451 Create Paranthesis Checker using stack in C [Hacktober2023]
  c/paranthesisChecker.c
  cpp/binary_Search.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#452 Created linearSearch.cpp
  cpp/linearSearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#453 Added insertion sort program in cpp
  cpp/insertionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#454 Issue : Implement a Data Structure Using Java
  data_structure/TreeNode DS Usinng Java/Main.java
  data_structure/TreeNode DS Usinng Java/TreeNode.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#455 Created unionOfTwoArray.cpp file in cpp folder
  cpp/unionOfTwoArray.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#456 Program to find saddle point
  cpp/saddle.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#457 Sort01TwoPointer.cpp
  cpp/Sort01TwoPointer.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#460 Added a Bookshop Program in Cpp to Buy Books and Add New Books
  cpp/Bookshop.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#461 Stack using Template Class
  cpp/Stack using Template Function.cpp
  data_structure/stack.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#464 Added double linked list in cpp
  data_structure/double_linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#465 ADDED linked list in cpp
  data_structure/linked_list/linked.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#468 Created Symmetric_Butterfly_Pattern.cpp in cpp.
  cpp/Symmetric_Butterfly_Pattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#469 Create Rotoate_Image.cpp
  LeetCodeQuestions/Rotoate_Image.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#471 Added the code for Kadane'sAlgorithm or MaximumSubarraySum
  LeetCodeQuestions/Kadane'sAlgorithm.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023

#473 added python program for finding prime numbers in given range
  python/prime_num_in_given_range.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2023
