Repository akkupy/codeDump, pull requests merged in 2023-09, with the labels that each got.

#235 Updated README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2023

#237 Simple Python based game
  python/Number_Finder_Game.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#196 Java OOP Concepts Recap
  java/Java OOP Fundamentals Assignment/Animal.java
  java/Java OOP Fundamentals Assignment/Animmal_Main.java
  java/Java OOP Fundamentals Assignment/Car.java
  java/Java OOP Fundamentals Assignment/Date.java
  java/Java OOP Fundamentals Assignment/DateTest.java
  java/Java OOP Fundamentals Assignment/Ford.java
  java/Java OOP Fundamentals Assignment/Item.java
  java/Java OOP Fundamentals Assignment/Item_Monster_Main.java
  java/Java OOP Fundamentals Assignment/Java Assignmemnt.pdf
  java/Java OOP Fundamentals Assignment/Main.java
  java/Java OOP Fundamentals Assignment/Monster.java
  java/Java OOP Fundamentals Assignment/MyOwnAutoShop.java
  java/Java OOP Fundamentals Assignment/ProjectClass.java
  java/Java OOP Fundamentals Assignment/Project_Main.java
  java/Java OOP Fundamentals Assignment/Question_1.java
  java/Java OOP Fundamentals Assignment/Question_2.java
  java/Java OOP Fundamentals Assignment/Question_3.java
  java/Java OOP Fundamentals Assignment/Question_4.java
  java/Java OOP Fundamentals Assignment/Question_5.java
  java/Java OOP Fundamentals Assignment/SavingsAccount.java
  java/Java OOP Fundamentals Assignment/Sedan.java
  java/Java OOP Fundamentals Assignment/Shape.java
  java/Java OOP Fundamentals Assignment/TestClass_SavingsAccount.java
  java/Java OOP Fundamentals Assignment/Truck.java
Labels: hacktoberfest-accepted

#199 Created treeIsomorfismWithMap.cpp
  cpp/treeIsomorfismWithMap.cpp
Labels: hacktoberfest-accepted

#201 LeetCode Problems
  python/12. Integer to Roman.py
  python/2. Add Two Numbers.py
  python/9. Palindrome Number.py
Labels: hacktoberfest-accepted

#210 eliminate_duplicate_nodes_in_linked_list.cpp
  cpp/eliminate_duplicate_nodes_in_linked_list.cpp
Labels: hacktoberfest-accepted

#211 Implement Palindrome program in C #208
  c/isPalindrome.c
  c/mergeSort.c
Labels: hacktoberfest-accepted

#217 Refactoring
  python/Check.py
  python/age.py
  python/powers of 2.py
Labels: hacktoberfest-accepted

#218 Create stack_list.py
  data_structure/stack_list.py
Labels: hacktoberfest-accepted

#219 Downward Triangle Pattern in Python , Issue : #216
  python/Downward_Triangle_Pattern.py
Labels: hacktoberfest-accepted

#222 Paper_Rock_Scissor-Game resolves #203
  python/Fibbonacci_Series_Class.py
  python/Paper_Rock_Scissor_Game.py
Labels: hacktoberfest-accepted

#225 Create dictionaryDataFetchFromValue.py
  python/dictionaryDataFetchFromValue.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#228 Added python program downward-triangle-pattern.py
  python/downward-triangle-pattern.py
Labels: hacktoberfest-accepted

#229 Added CPP Problem Longest Palindromic Substring
  cpp/Longest_Palindromic.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#231 #216 Downward triangle created
  data_structure/stack_using_list.py
  python/downward_triangle.py
Labels: hacktoberfest-accepted

#232 Created MaxHeap.cpp
  cpp/MaxHeap.cpp
Labels: duplicate
